// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cmd/demo/proto/api.proto

package proto

import (
	context "context"
	fmt "fmt"
	_ "github.com/binchencoder/ease-gateway/httpoptions"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GreetingRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Age                  int32    `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GreetingRequest) Reset()         { *m = GreetingRequest{} }
func (m *GreetingRequest) String() string { return proto.CompactTextString(m) }
func (*GreetingRequest) ProtoMessage()    {}
func (*GreetingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9163d5e34ccdff5, []int{0}
}

func (m *GreetingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GreetingRequest.Unmarshal(m, b)
}
func (m *GreetingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GreetingRequest.Marshal(b, m, deterministic)
}
func (m *GreetingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GreetingRequest.Merge(m, src)
}
func (m *GreetingRequest) XXX_Size() int {
	return xxx_messageInfo_GreetingRequest.Size(m)
}
func (m *GreetingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GreetingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GreetingRequest proto.InternalMessageInfo

func (m *GreetingRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GreetingRequest) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

type GreetingResponse struct {
	Greeting             string   `protobuf:"bytes,1,opt,name=greeting,proto3" json:"greeting,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GreetingResponse) Reset()         { *m = GreetingResponse{} }
func (m *GreetingResponse) String() string { return proto.CompactTextString(m) }
func (*GreetingResponse) ProtoMessage()    {}
func (*GreetingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9163d5e34ccdff5, []int{1}
}

func (m *GreetingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GreetingResponse.Unmarshal(m, b)
}
func (m *GreetingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GreetingResponse.Marshal(b, m, deterministic)
}
func (m *GreetingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GreetingResponse.Merge(m, src)
}
func (m *GreetingResponse) XXX_Size() int {
	return xxx_messageInfo_GreetingResponse.Size(m)
}
func (m *GreetingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GreetingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GreetingResponse proto.InternalMessageInfo

func (m *GreetingResponse) GetGreeting() string {
	if m != nil {
		return m.Greeting
	}
	return ""
}

func init() {
	proto.RegisterType((*GreetingRequest)(nil), "proto.GreetingRequest")
	proto.RegisterType((*GreetingResponse)(nil), "proto.GreetingResponse")
}

func init() { proto.RegisterFile("cmd/demo/proto/api.proto", fileDescriptor_c9163d5e34ccdff5) }

var fileDescriptor_c9163d5e34ccdff5 = []byte{
	// 308 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x48, 0xce, 0x4d, 0xd1,
	0x4f, 0x49, 0xcd, 0xcd, 0xd7, 0x2f, 0x28, 0xca, 0x2f, 0xc9, 0xd7, 0x4f, 0x2c, 0xc8, 0xd4, 0x03,
	0xb3, 0x84, 0x58, 0xc1, 0x94, 0x94, 0x6c, 0x46, 0x49, 0x49, 0x41, 0x7e, 0x41, 0x49, 0x66, 0x7e,
	0x5e, 0xb1, 0x7e, 0x62, 0x5e, 0x5e, 0x7e, 0x49, 0x22, 0x98, 0x0d, 0x51, 0xa5, 0x64, 0xce, 0xc5,
	0xef, 0x5e, 0x94, 0x9a, 0x5a, 0x92, 0x99, 0x97, 0x1e, 0x94, 0x5a, 0x58, 0x9a, 0x5a, 0x5c, 0x22,
	0x24, 0xc4, 0xc5, 0x92, 0x97, 0x98, 0x9b, 0x2a, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x19, 0x04, 0x66,
	0x0b, 0x09, 0x70, 0x31, 0x27, 0xa6, 0xa7, 0x4a, 0x30, 0x29, 0x30, 0x6a, 0xb0, 0x06, 0x81, 0x98,
	0x4a, 0x7a, 0x5c, 0x02, 0x08, 0x8d, 0xc5, 0x05, 0xf9, 0x79, 0xc5, 0xa9, 0x42, 0x52, 0x5c, 0x1c,
	0xe9, 0x50, 0x31, 0xa8, 0x6e, 0x38, 0xdf, 0xe8, 0x34, 0x23, 0x17, 0x8b, 0x4b, 0x6a, 0x6e, 0xbe,
	0x50, 0x18, 0x17, 0x07, 0x4c, 0xa3, 0x90, 0x18, 0xc4, 0x15, 0x7a, 0x68, 0x4e, 0x90, 0x12, 0xc7,
	0x10, 0x87, 0xd8, 0xa0, 0x24, 0x79, 0xea, 0xb3, 0x89, 0xa8, 0x90, 0xb0, 0x7e, 0x99, 0xa1, 0x3e,
	0xcc, 0x64, 0xfd, 0x6a, 0x90, 0x0b, 0x6b, 0x85, 0xdc, 0x10, 0x3e, 0x71, 0xcb, 0x2f, 0x72, 0x2d,
	0x4b, 0x2d, 0x22, 0xdd, 0x78, 0x06, 0x03, 0x46, 0x29, 0xe5, 0x57, 0x9f, 0x4d, 0xe4, 0x39, 0xb6,
	0x4d, 0xfd, 0xff, 0x9f, 0x5d, 0x88, 0xa3, 0x20, 0xbf, 0xa8, 0x04, 0x64, 0xbc, 0x14, 0x37, 0x88,
	0x2c, 0x2e, 0x48, 0x4c, 0x4e, 0x8d, 0x37, 0x50, 0x60, 0x34, 0x3a, 0xc3, 0xc8, 0xc5, 0x0a, 0xf2,
	0x8d, 0xe1, 0x10, 0xf1, 0xce, 0x46, 0xbc, 0xde, 0x71, 0x32, 0xe5, 0x52, 0x4c, 0xce, 0xcf, 0xd5,
	0x4b, 0xca, 0xcc, 0x4b, 0xce, 0x48, 0xcd, 0x4b, 0xce, 0x4f, 0x49, 0x2d, 0xd2, 0x2b, 0xce, 0xae,
	0xcc, 0x49, 0xd2, 0x03, 0x25, 0x2d, 0x88, 0xf1, 0x4e, 0x7c, 0x30, 0xf3, 0x03, 0x40, 0xdc, 0xe2,
	0x00, 0x86, 0x24, 0x36, 0xb0, 0x84, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x2b, 0xd0, 0x00, 0xa3,
	0x85, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DemoClient is the client API for Demo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DemoClient interface {
	Greeting(ctx context.Context, in *GreetingRequest, opts ...grpc.CallOption) (*GreetingResponse, error)
	GreetingForEver(ctx context.Context, in *GreetingRequest, opts ...grpc.CallOption) (Demo_GreetingForEverClient, error)
}

type demoClient struct {
	cc grpc.ClientConnInterface
}

func NewDemoClient(cc grpc.ClientConnInterface) DemoClient {
	return &demoClient{cc}
}

func (c *demoClient) Greeting(ctx context.Context, in *GreetingRequest, opts ...grpc.CallOption) (*GreetingResponse, error) {
	out := new(GreetingResponse)
	err := c.cc.Invoke(ctx, "/proto.Demo/Greeting", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *demoClient) GreetingForEver(ctx context.Context, in *GreetingRequest, opts ...grpc.CallOption) (Demo_GreetingForEverClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Demo_serviceDesc.Streams[0], "/proto.Demo/GreetingForEver", opts...)
	if err != nil {
		return nil, err
	}
	x := &demoGreetingForEverClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Demo_GreetingForEverClient interface {
	Recv() (*GreetingResponse, error)
	grpc.ClientStream
}

type demoGreetingForEverClient struct {
	grpc.ClientStream
}

func (x *demoGreetingForEverClient) Recv() (*GreetingResponse, error) {
	m := new(GreetingResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// DemoServer is the server API for Demo service.
type DemoServer interface {
	Greeting(context.Context, *GreetingRequest) (*GreetingResponse, error)
	GreetingForEver(*GreetingRequest, Demo_GreetingForEverServer) error
}

// UnimplementedDemoServer can be embedded to have forward compatible implementations.
type UnimplementedDemoServer struct {
}

func (*UnimplementedDemoServer) Greeting(ctx context.Context, req *GreetingRequest) (*GreetingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Greeting not implemented")
}
func (*UnimplementedDemoServer) GreetingForEver(req *GreetingRequest, srv Demo_GreetingForEverServer) error {
	return status.Errorf(codes.Unimplemented, "method GreetingForEver not implemented")
}

func RegisterDemoServer(s *grpc.Server, srv DemoServer) {
	s.RegisterService(&_Demo_serviceDesc, srv)
}

func _Demo_Greeting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GreetingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DemoServer).Greeting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Demo/Greeting",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DemoServer).Greeting(ctx, req.(*GreetingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Demo_GreetingForEver_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GreetingRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DemoServer).GreetingForEver(m, &demoGreetingForEverServer{stream})
}

type Demo_GreetingForEverServer interface {
	Send(*GreetingResponse) error
	grpc.ServerStream
}

type demoGreetingForEverServer struct {
	grpc.ServerStream
}

func (x *demoGreetingForEverServer) Send(m *GreetingResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _Demo_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Demo",
	HandlerType: (*DemoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Greeting",
			Handler:    _Demo_Greeting_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GreetingForEver",
			Handler:       _Demo_GreetingForEver_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "cmd/demo/proto/api.proto",
}

// Demo1Client is the client API for Demo1 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type Demo1Client interface {
	Greeting(ctx context.Context, in *GreetingRequest, opts ...grpc.CallOption) (*GreetingResponse, error)
	GreetingForEver(ctx context.Context, in *GreetingRequest, opts ...grpc.CallOption) (Demo1_GreetingForEverClient, error)
}

type demo1Client struct {
	cc grpc.ClientConnInterface
}

func NewDemo1Client(cc grpc.ClientConnInterface) Demo1Client {
	return &demo1Client{cc}
}

func (c *demo1Client) Greeting(ctx context.Context, in *GreetingRequest, opts ...grpc.CallOption) (*GreetingResponse, error) {
	out := new(GreetingResponse)
	err := c.cc.Invoke(ctx, "/proto.Demo1/Greeting", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *demo1Client) GreetingForEver(ctx context.Context, in *GreetingRequest, opts ...grpc.CallOption) (Demo1_GreetingForEverClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Demo1_serviceDesc.Streams[0], "/proto.Demo1/GreetingForEver", opts...)
	if err != nil {
		return nil, err
	}
	x := &demo1GreetingForEverClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Demo1_GreetingForEverClient interface {
	Recv() (*GreetingResponse, error)
	grpc.ClientStream
}

type demo1GreetingForEverClient struct {
	grpc.ClientStream
}

func (x *demo1GreetingForEverClient) Recv() (*GreetingResponse, error) {
	m := new(GreetingResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Demo1Server is the server API for Demo1 service.
type Demo1Server interface {
	Greeting(context.Context, *GreetingRequest) (*GreetingResponse, error)
	GreetingForEver(*GreetingRequest, Demo1_GreetingForEverServer) error
}

// UnimplementedDemo1Server can be embedded to have forward compatible implementations.
type UnimplementedDemo1Server struct {
}

func (*UnimplementedDemo1Server) Greeting(ctx context.Context, req *GreetingRequest) (*GreetingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Greeting not implemented")
}
func (*UnimplementedDemo1Server) GreetingForEver(req *GreetingRequest, srv Demo1_GreetingForEverServer) error {
	return status.Errorf(codes.Unimplemented, "method GreetingForEver not implemented")
}

func RegisterDemo1Server(s *grpc.Server, srv Demo1Server) {
	s.RegisterService(&_Demo1_serviceDesc, srv)
}

func _Demo1_Greeting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GreetingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Demo1Server).Greeting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Demo1/Greeting",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Demo1Server).Greeting(ctx, req.(*GreetingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Demo1_GreetingForEver_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GreetingRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(Demo1Server).GreetingForEver(m, &demo1GreetingForEverServer{stream})
}

type Demo1_GreetingForEverServer interface {
	Send(*GreetingResponse) error
	grpc.ServerStream
}

type demo1GreetingForEverServer struct {
	grpc.ServerStream
}

func (x *demo1GreetingForEverServer) Send(m *GreetingResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _Demo1_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Demo1",
	HandlerType: (*Demo1Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Greeting",
			Handler:    _Demo1_Greeting_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GreetingForEver",
			Handler:       _Demo1_GreetingForEver_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "cmd/demo/proto/api.proto",
}
