// Code generated by protoc-gen-grpc-gateway. DO NOT EDIT.
// source: cmd/demo/proto/api.proto

/*
Package proto is a reverse proxy.

It translates gRPC into RESTful JSON APIs.
*/
package proto

import (
	"context"
	"io"
	"net/http"
	"regexp"
	"strings"
	"sync"
	"unicode/utf8"

	"github.com/binchencoder/ease-gateway/gateway/runtime"
	vexpb "github.com/binchencoder/gateway-proto/data"
	fpb "github.com/binchencoder/gateway-proto/frontend"
	lgr "github.com/binchencoder/letsgo/grpc"
	"github.com/binchencoder/skylb-api/balancer"
	"github.com/binchencoder/skylb-api/client"
	"github.com/binchencoder/skylb-api/client/option"
	skypb "github.com/binchencoder/skylb-api/proto"
	"github.com/golang/protobuf/proto"
	"github.com/grpc-ecosystem/grpc-gateway/utilities"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/naming"
	"google.golang.org/grpc/status"
)

// Suppress "imported and not used" errors
var _ codes.Code
var _ io.Reader
var _ status.Status
var _ = runtime.String
var _ = utilities.NewDoubleArray

// var _ = descriptor.ForMessage
var _ sync.RWMutex
var _ proto.Message
var _ context.Context
var _ grpc.ClientConn
var _ client.ServiceCli
var _ vexpb.ServiceId
var _ = http.MethodGet
var _ regexp.Regexp
var _ = balancer.ConsistentHashing
var _ option.BalancerCreator
var _ naming.Resolver
var _ strings.Reader
var _ = utf8.UTFMax

// TODO (jiezmo): check if there is any rule before create this var.
var cmd_demo_proto_api_error = lgr.ToGrpcError(codes.InvalidArgument, &fpb.Error{Code: fpb.ErrorCode_BADPARAM_ERROR, Params: []string{"Validation error"}})

// Validation methods start

// Validation methods done

var (
	filter_Demo_Greeting_0 = &utilities.DoubleArray{Encoding: map[string]int{"name": 0}, Base: []int{1, 1, 0}, Check: []int{0, 1, 2}}
)

func request_Demo_Greeting_0(ctx context.Context, marshaler runtime.Marshaler, client DemoClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq GreetingRequest
	var metadata runtime.ServerMetadata
	spec := internal_Demo_CUSTOM_EASE_GATEWAY_TEST_spec

	var (
		val string
		ok  bool
		err error
		_   = err
	)

	val, ok = pathParams["name"]
	if !ok {
		runtime.RequestHandled(ctx, spec, "Demo", "Greeting", nil, &metadata, err)
		return nil, metadata, status.Errorf(codes.InvalidArgument, "missing parameter %s", "name")
	}

	protoReq.Name, err = runtime.String(val)

	if err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "type mismatch, parameter: %s, error: %v", "name", err)
	}

	if err := req.ParseForm(); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}
	if err := runtime.PopulateQueryParameters(&protoReq, req.Form, filter_Demo_Greeting_0); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	// Only hook up for non-stream call for now.

	runtime.RequestParsed(ctx, spec, "Demo", "Greeting", &protoReq, &metadata)
	ctx = runtime.PreLoadBalance(ctx, "ROUND_ROBIN", "", &protoReq)
	msg, err := client.Greeting(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	// if err != nil {
	// 	grpclog.Errorf("client.%s returns error: %v", "Greeting", err)
	// }
	runtime.RequestHandled(ctx, spec, "Demo", "Greeting", msg, &metadata, err)
	return msg, metadata, err

}

func local_request_Demo_Greeting_0(ctx context.Context, marshaler runtime.Marshaler, server DemoServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq GreetingRequest
	var metadata runtime.ServerMetadata

	var (
		val string
		ok  bool
		err error
		_   = err
	)

	val, ok = pathParams["name"]
	if !ok {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "missing parameter %s", "name")
	}

	protoReq.Name, err = runtime.String(val)

	if err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "type mismatch, parameter: %s, error: %v", "name", err)
	}

	if err := runtime.PopulateQueryParameters(&protoReq, req.URL.Query(), filter_Demo_Greeting_0); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := server.Greeting(ctx, &protoReq)
	return msg, metadata, err

}

var (
	filter_Demo1_Greeting_0 = &utilities.DoubleArray{Encoding: map[string]int{"name": 0}, Base: []int{1, 1, 0}, Check: []int{0, 1, 2}}
)

func request_Demo1_Greeting_0(ctx context.Context, marshaler runtime.Marshaler, client Demo1Client, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq GreetingRequest
	var metadata runtime.ServerMetadata
	spec := internal_Demo1_SHARED_TEST_SERVER_SERVICE_spec

	var (
		val string
		ok  bool
		err error
		_   = err
	)

	val, ok = pathParams["name"]
	if !ok {
		runtime.RequestHandled(ctx, spec, "Demo1", "Greeting", nil, &metadata, err)
		return nil, metadata, status.Errorf(codes.InvalidArgument, "missing parameter %s", "name")
	}

	protoReq.Name, err = runtime.String(val)

	if err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "type mismatch, parameter: %s, error: %v", "name", err)
	}

	if err := req.ParseForm(); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}
	if err := runtime.PopulateQueryParameters(&protoReq, req.Form, filter_Demo1_Greeting_0); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	// Only hook up for non-stream call for now.

	runtime.RequestParsed(ctx, spec, "Demo1", "Greeting", &protoReq, &metadata)
	ctx = runtime.PreLoadBalance(ctx, "ROUND_ROBIN", "", &protoReq)
	msg, err := client.Greeting(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	// if err != nil {
	// 	grpclog.Errorf("client.%s returns error: %v", "Greeting", err)
	// }
	runtime.RequestHandled(ctx, spec, "Demo1", "Greeting", msg, &metadata, err)
	return msg, metadata, err

}

func local_request_Demo1_Greeting_0(ctx context.Context, marshaler runtime.Marshaler, server Demo1Server, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq GreetingRequest
	var metadata runtime.ServerMetadata

	var (
		val string
		ok  bool
		err error
		_   = err
	)

	val, ok = pathParams["name"]
	if !ok {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "missing parameter %s", "name")
	}

	protoReq.Name, err = runtime.String(val)

	if err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "type mismatch, parameter: %s, error: %v", "name", err)
	}

	if err := runtime.PopulateQueryParameters(&protoReq, req.URL.Query(), filter_Demo1_Greeting_0); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := server.Greeting(ctx, &protoReq)
	return msg, metadata, err

}

// Register itself to runtime.
func init() {
	var s *runtime.Service
	var spec *skypb.ServiceSpec

	_ = s
	_ = spec

	spec = internal_Demo_CUSTOM_EASE_GATEWAY_TEST_spec
	s = &runtime.Service{
		Spec:     *spec,
		Name:     "Demo",
		Register: RegisterDemoHandlerFromEndpoint,
		Enable:   EnableDemo_Service,
		Disable:  DisableDemo_Service,
	}

	runtime.AddService(s, Enable_CUSTOM_EASE_GATEWAY_TEST__namespace_0__portname_ServiceGroup, Disable_CUSTOM_EASE_GATEWAY_TEST__namespace_0__portname_ServiceGroup)

	spec = internal_Demo1_SHARED_TEST_SERVER_SERVICE_spec
	s = &runtime.Service{
		Spec:     *spec,
		Name:     "Demo1",
		Register: RegisterDemo1HandlerFromEndpoint,
		Enable:   EnableDemo1_Service,
		Disable:  DisableDemo1_Service,
	}

	runtime.AddService(s, Enable_SHARED_TEST_SERVER_SERVICE__namespace_0__portname_ServiceGroup, Disable_SHARED_TEST_SERVER_SERVICE__namespace_0__portname_ServiceGroup)

}

// RegisterDemoHandlerFromEndpoint is same as RegisterDemoHandler but
// automatically dials to "endpoint" and closes the connection when "ctx" gets done.
func RegisterDemoHandlerFromEndpoint(mux *runtime.ServeMux) (err error) {
	// conn, err := grpc.Dial(endpoint, opts...)
	// if err != nil {
	// 	return err
	// }
	// defer func() {
	// 	if err != nil {
	// 		if cerr := conn.Close(); cerr != nil {
	// 			grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
	// 		}
	// 		return
	// 	}
	// 	go func() {
	// 		<-ctx.Done()
	// 		if cerr := conn.Close(); cerr != nil {
	// 			grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
	// 		}
	// 	}()
	// }()

	// return RegisterDemoHandler(ctx, mux, conn)
	return RegisterDemoHandler(nil, mux, nil)
}

// RegisterDemoHandler registers the http handlers for service Demo to "mux".
// The handlers forward requests to the grpc endpoint over "conn".
func RegisterDemoHandler(ctx context.Context, mux *runtime.ServeMux, conn *grpc.ClientConn) error {
	return RegisterDemoHandlerClient(ctx, mux, NewDemoClient(conn))
}

// RegisterDemoHandlerClient registers the http handlers for service Demo
// to "mux". The handlers forward requests to the grpc endpoint over the given implementation of "DemoClient".
// Note: the gRPC framework executes interceptors within the gRPC handler. If the passed in "DemoClient"
// doesn't go through the normal gRPC flow (creating a gRPC client etc.) then it will be up to the passed in
// "DemoClient" to call the correct interceptors.
func RegisterDemoHandlerClient(ctx context.Context, mux *runtime.ServeMux, client DemoClient) error {
	spec := internal_Demo_CUSTOM_EASE_GATEWAY_TEST_spec

	runtime.AddMethod(spec, "Demo", "Greeting", "/v1/greeting/{name}", "GET", true, false, false, "UNSPECIFIED", "EASE_GATEWAY", "EASE_AUTH_TOKEN", "")
	mux.Handle("GET", pattern_Demo_Greeting_0, vexpb.ServiceId_CUSTOM_EASE_GATEWAY_TEST, func(inctx context.Context, w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		// TODO(mojz): review all locking/unlocking logic.
		// internal_CUSTOM_EASE_GATEWAY_TEST__namespace_0__portname_lock.RLock()
		// defer internal_CUSTOM_EASE_GATEWAY_TEST__namespace_0__portname_lock.RUnlock()
		client := internal_Demo_CUSTOM_EASE_GATEWAY_TEST_client
		if client == nil {
			runtime.DefaultOtherErrorHandler(w, req, "service disabled", http.StatusInternalServerError)
			return
		}

		ctx, err := runtime.RequestAccepted(inctx, internal_Demo_CUSTOM_EASE_GATEWAY_TEST_spec, "Demo", "Greeting", w, req)
		if err != nil {
			// grpclog.Errorf("runtime.RequestAccepted returns error: %v", err)
			runtime.HTTPError(ctx, nil, &runtime.JSONBuiltin{}, w, req, err)
			return
		}
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		rctx, err := runtime.AnnotateContext(ctx, mux, req)
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_Demo_Greeting_0(rctx, inboundMarshaler, client, req, pathParams)
		ctx = runtime.NewServerMetadataContext(ctx, md)
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_Demo_Greeting_0(ctx, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	return nil
}

func Disable_CUSTOM_EASE_GATEWAY_TEST__namespace_0__portname_ServiceGroup() {
	// internal_CUSTOM_EASE_GATEWAY_TEST__namespace_0__portname_lock.Lock()
	// defer internal_CUSTOM_EASE_GATEWAY_TEST__namespace_0__portname_lock.Unlock()
	if internal_CUSTOM_EASE_GATEWAY_TEST__namespace_0__portname_skycli != nil {
		spec := internal_Demo_CUSTOM_EASE_GATEWAY_TEST_spec
		sg := runtime.GetServiceGroup(spec)
		for _, svc := range sg.Services {
			svc.Disable()
		}

		internal_Demo_CUSTOM_EASE_GATEWAY_TEST_client = nil
		internal_CUSTOM_EASE_GATEWAY_TEST__namespace_0__portname_skycli.Shutdown()
		internal_CUSTOM_EASE_GATEWAY_TEST__namespace_0__portname_skycli = nil
	}
}

func Enable_CUSTOM_EASE_GATEWAY_TEST__namespace_0__portname_ServiceGroup() {
	// internal_CUSTOM_EASE_GATEWAY_TEST__namespace_0__portname_lock.Lock()
	// defer internal_CUSTOM_EASE_GATEWAY_TEST__namespace_0__portname_lock.Unlock()

	internal_CUSTOM_EASE_GATEWAY_TEST__namespace_0__portname_skycli = client.NewServiceCli(runtime.CallerServiceId)

	// Resolve service
	spec := internal_Demo_CUSTOM_EASE_GATEWAY_TEST_spec

	internal_CUSTOM_EASE_GATEWAY_TEST__namespace_0__portname_skycli.Resolve(spec)

	internal_CUSTOM_EASE_GATEWAY_TEST__namespace_0__portname_skycli.EnableResolveFullEps()
	internal_CUSTOM_EASE_GATEWAY_TEST__namespace_0__portname_skycli.Start(func(spec *skypb.ServiceSpec, conn *grpc.ClientConn) {
		sg := runtime.GetServiceGroup(spec)
		for _, svc := range sg.Services {
			svc.Enable(spec, conn)
		}
	})
}

func EnableDemo_Service(spec *skypb.ServiceSpec, conn *grpc.ClientConn) {
	internal_Demo_CUSTOM_EASE_GATEWAY_TEST_client = NewDemoClient(conn)
}

func DisableDemo_Service() {
	internal_Demo_CUSTOM_EASE_GATEWAY_TEST_client = nil
}

var (
	pattern_Demo_Greeting_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1, 1, 0, 4, 1, 5, 2}, []string{"v1", "greeting", "name"}, "", runtime.AssumeColonVerbOpt(true)))
)

var (
	forward_Demo_Greeting_0 = runtime.ForwardResponseMessage
)

var (
	internal_Demo_CUSTOM_EASE_GATEWAY_TEST_spec   = client.NewServiceSpec("namespace_0", vexpb.ServiceId_CUSTOM_EASE_GATEWAY_TEST, "portname")
	internal_Demo_CUSTOM_EASE_GATEWAY_TEST_client DemoClient

	internal_CUSTOM_EASE_GATEWAY_TEST__namespace_0__portname_skycli client.ServiceCli

	internal_CUSTOM_EASE_GATEWAY_TEST__namespace_0__portname_lock = sync.RWMutex{}
)

// RegisterDemo1HandlerFromEndpoint is same as RegisterDemo1Handler but
// automatically dials to "endpoint" and closes the connection when "ctx" gets done.
func RegisterDemo1HandlerFromEndpoint(mux *runtime.ServeMux) (err error) {
	// conn, err := grpc.Dial(endpoint, opts...)
	// if err != nil {
	// 	return err
	// }
	// defer func() {
	// 	if err != nil {
	// 		if cerr := conn.Close(); cerr != nil {
	// 			grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
	// 		}
	// 		return
	// 	}
	// 	go func() {
	// 		<-ctx.Done()
	// 		if cerr := conn.Close(); cerr != nil {
	// 			grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
	// 		}
	// 	}()
	// }()

	// return RegisterDemo1Handler(ctx, mux, conn)
	return RegisterDemo1Handler(nil, mux, nil)
}

// RegisterDemo1Handler registers the http handlers for service Demo1 to "mux".
// The handlers forward requests to the grpc endpoint over "conn".
func RegisterDemo1Handler(ctx context.Context, mux *runtime.ServeMux, conn *grpc.ClientConn) error {
	return RegisterDemo1HandlerClient(ctx, mux, NewDemo1Client(conn))
}

// RegisterDemo1HandlerClient registers the http handlers for service Demo1
// to "mux". The handlers forward requests to the grpc endpoint over the given implementation of "Demo1Client".
// Note: the gRPC framework executes interceptors within the gRPC handler. If the passed in "Demo1Client"
// doesn't go through the normal gRPC flow (creating a gRPC client etc.) then it will be up to the passed in
// "Demo1Client" to call the correct interceptors.
func RegisterDemo1HandlerClient(ctx context.Context, mux *runtime.ServeMux, client Demo1Client) error {
	spec := internal_Demo1_SHARED_TEST_SERVER_SERVICE_spec

	runtime.AddMethod(spec, "Demo1", "Greeting", "/v1/greeting/{name}", "GET", true, false, false, "UNSPECIFIED", "EASE_GATEWAY", "EASE_AUTH_TOKEN", "")
	mux.Handle("GET", pattern_Demo1_Greeting_0, vexpb.ServiceId_SHARED_TEST_SERVER_SERVICE, func(inctx context.Context, w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		// TODO(mojz): review all locking/unlocking logic.
		// internal_SHARED_TEST_SERVER_SERVICE__namespace_0__portname_lock.RLock()
		// defer internal_SHARED_TEST_SERVER_SERVICE__namespace_0__portname_lock.RUnlock()
		client := internal_Demo1_SHARED_TEST_SERVER_SERVICE_client
		if client == nil {
			runtime.DefaultOtherErrorHandler(w, req, "service disabled", http.StatusInternalServerError)
			return
		}

		ctx, err := runtime.RequestAccepted(inctx, internal_Demo1_SHARED_TEST_SERVER_SERVICE_spec, "Demo1", "Greeting", w, req)
		if err != nil {
			// grpclog.Errorf("runtime.RequestAccepted returns error: %v", err)
			runtime.HTTPError(ctx, nil, &runtime.JSONBuiltin{}, w, req, err)
			return
		}
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		rctx, err := runtime.AnnotateContext(ctx, mux, req)
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_Demo1_Greeting_0(rctx, inboundMarshaler, client, req, pathParams)
		ctx = runtime.NewServerMetadataContext(ctx, md)
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_Demo1_Greeting_0(ctx, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	return nil
}

func Disable_SHARED_TEST_SERVER_SERVICE__namespace_0__portname_ServiceGroup() {
	// internal_SHARED_TEST_SERVER_SERVICE__namespace_0__portname_lock.Lock()
	// defer internal_SHARED_TEST_SERVER_SERVICE__namespace_0__portname_lock.Unlock()
	if internal_SHARED_TEST_SERVER_SERVICE__namespace_0__portname_skycli != nil {
		spec := internal_Demo1_SHARED_TEST_SERVER_SERVICE_spec
		sg := runtime.GetServiceGroup(spec)
		for _, svc := range sg.Services {
			svc.Disable()
		}

		internal_Demo1_SHARED_TEST_SERVER_SERVICE_client = nil
		internal_SHARED_TEST_SERVER_SERVICE__namespace_0__portname_skycli.Shutdown()
		internal_SHARED_TEST_SERVER_SERVICE__namespace_0__portname_skycli = nil
	}
}

func Enable_SHARED_TEST_SERVER_SERVICE__namespace_0__portname_ServiceGroup() {
	// internal_SHARED_TEST_SERVER_SERVICE__namespace_0__portname_lock.Lock()
	// defer internal_SHARED_TEST_SERVER_SERVICE__namespace_0__portname_lock.Unlock()

	internal_SHARED_TEST_SERVER_SERVICE__namespace_0__portname_skycli = client.NewServiceCli(runtime.CallerServiceId)

	// Resolve service
	spec := internal_Demo1_SHARED_TEST_SERVER_SERVICE_spec

	internal_SHARED_TEST_SERVER_SERVICE__namespace_0__portname_skycli.Resolve(spec)

	internal_SHARED_TEST_SERVER_SERVICE__namespace_0__portname_skycli.EnableResolveFullEps()
	internal_SHARED_TEST_SERVER_SERVICE__namespace_0__portname_skycli.Start(func(spec *skypb.ServiceSpec, conn *grpc.ClientConn) {
		sg := runtime.GetServiceGroup(spec)
		for _, svc := range sg.Services {
			svc.Enable(spec, conn)
		}
	})
}

func EnableDemo1_Service(spec *skypb.ServiceSpec, conn *grpc.ClientConn) {
	internal_Demo1_SHARED_TEST_SERVER_SERVICE_client = NewDemo1Client(conn)
}

func DisableDemo1_Service() {
	internal_Demo1_SHARED_TEST_SERVER_SERVICE_client = nil
}

var (
	pattern_Demo1_Greeting_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1, 1, 0, 4, 1, 5, 2}, []string{"v1", "greeting", "name"}, "", runtime.AssumeColonVerbOpt(true)))
)

var (
	forward_Demo1_Greeting_0 = runtime.ForwardResponseMessage
)

var (
	internal_Demo1_SHARED_TEST_SERVER_SERVICE_spec   = client.NewServiceSpec("namespace_0", vexpb.ServiceId_SHARED_TEST_SERVER_SERVICE, "portname")
	internal_Demo1_SHARED_TEST_SERVER_SERVICE_client Demo1Client

	internal_SHARED_TEST_SERVER_SERVICE__namespace_0__portname_skycli client.ServiceCli

	internal_SHARED_TEST_SERVER_SERVICE__namespace_0__portname_lock = sync.RWMutex{}
)
