package(
    default_visibility = ["//visibility:public"],
)

java_library(
    name = "roundrobin",
    srcs = glob(["*.java"]),
    deps = [
        "//skylb-api/java/src/main/java/com/jingoal/skylb/healthcheck",
        "//third-party-java/dependencies/lib:grpc-1.18.0",
        "//third-party-java/dependencies/lib:jsr305-3.0.1",
        "//third-party-java/dependencies/lib:slf4j-api-1.7.21",
    ],
)
