package(
    default_visibility = ["//visibility:public"],
)

java_library(
    name = "healthcheck",
    srcs = glob(["*.java"]),
    deps = [
        "//third-party-java/dependencies/lib:grpc-1.18.0",
    ],
)
