// Code generated by protoc-gen-grpc-gateway. DO NOT EDIT.
// source: cmd/stress/proto/api.proto

/*
Package proto is a reverse proxy.

It translates gRPC into RESTful JSON APIs.
*/
package proto

import (
	"context"
	"io"
	"net/http"
	"regexp"
	"strings"
	"sync"
	"unicode/utf8"

	"github.com/binchencoder/ease-gateway/gateway/runtime"
	vexpb "github.com/binchencoder/gateway-proto/data"
	fpb "github.com/binchencoder/gateway-proto/frontend"
	lgr "github.com/binchencoder/letsgo/grpc"
	"github.com/binchencoder/skylb-api/balancer"
	"github.com/binchencoder/skylb-api/client"
	"github.com/binchencoder/skylb-api/client/option"
	skypb "github.com/binchencoder/skylb-api/proto"
	"github.com/golang/protobuf/proto"
	"github.com/grpc-ecosystem/grpc-gateway/utilities"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/naming"
	"google.golang.org/grpc/status"
)

// Suppress "imported and not used" errors
var _ codes.Code
var _ io.Reader
var _ status.Status
var _ = runtime.String
var _ = utilities.NewDoubleArray

// var _ = descriptor.ForMessage
var _ sync.RWMutex
var _ proto.Message
var _ context.Context
var _ grpc.ClientConn
var _ client.ServiceCli
var _ vexpb.ServiceId
var _ = http.MethodGet
var _ regexp.Regexp
var _ = balancer.ConsistentHashing
var _ option.BalancerCreator
var _ naming.Resolver
var _ strings.Reader
var _ = utf8.UTFMax

// TODO (jiezmo): check if there is any rule before create this var.
var cmd_stress_proto_api_error = lgr.ToGrpcError(codes.InvalidArgument, &fpb.Error{Code: fpb.ErrorCode_BADPARAM_ERROR, Params: []string{"Validation error"}})

// Validation methods start

// Validation methods done

func request_StressService_SayHello_0(ctx context.Context, marshaler runtime.Marshaler, client StressServiceClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq SayHelloReq
	var metadata runtime.ServerMetadata
	spec := internal_StressService_SHARED_TEST_SERVER_SERVICE_spec

	var (
		val string
		e   int32
		ok  bool
		err error
		_   = err
	)

	val, ok = pathParams["name"]
	if !ok {
		runtime.RequestHandled(ctx, spec, "StressService", "SayHello", nil, &metadata, err)
		return nil, metadata, status.Errorf(codes.InvalidArgument, "missing parameter %s", "name")
	}

	protoReq.Name, err = runtime.String(val)

	if err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "type mismatch, parameter: %s, error: %v", "name", err)
	}

	val, ok = pathParams["gender"]
	if !ok {
		runtime.RequestHandled(ctx, spec, "StressService", "SayHello", nil, &metadata, err)
		return nil, metadata, status.Errorf(codes.InvalidArgument, "missing parameter %s", "gender")
	}

	e, err = runtime.Enum(val, Gender_value)

	if err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "type mismatch, parameter: %s, error: %v", "gender", err)
	}

	protoReq.Gender = Gender(e)

	// Only hook up for non-stream call for now.

	runtime.RequestParsed(ctx, spec, "StressService", "SayHello", &protoReq, &metadata)
	ctx = runtime.PreLoadBalance(ctx, "ROUND_ROBIN", "", &protoReq)
	msg, err := client.SayHello(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	// if err != nil {
	// 	grpclog.Errorf("client.%s returns error: %v", "SayHello", err)
	// }
	runtime.RequestHandled(ctx, spec, "StressService", "SayHello", msg, &metadata, err)
	return msg, metadata, err

}

func local_request_StressService_SayHello_0(ctx context.Context, marshaler runtime.Marshaler, server StressServiceServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq SayHelloReq
	var metadata runtime.ServerMetadata

	var (
		val string
		e   int32
		ok  bool
		err error
		_   = err
	)

	val, ok = pathParams["name"]
	if !ok {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "missing parameter %s", "name")
	}

	protoReq.Name, err = runtime.String(val)

	if err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "type mismatch, parameter: %s, error: %v", "name", err)
	}

	val, ok = pathParams["gender"]
	if !ok {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "missing parameter %s", "gender")
	}

	e, err = runtime.Enum(val, Gender_value)

	if err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "type mismatch, parameter: %s, error: %v", "gender", err)
	}

	protoReq.Gender = Gender(e)

	msg, err := server.SayHello(ctx, &protoReq)
	return msg, metadata, err

}

func request_StressService_SayHelloDisabled_0(ctx context.Context, marshaler runtime.Marshaler, client StressServiceClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq SayHelloReq
	var metadata runtime.ServerMetadata
	spec := internal_StressService_SHARED_TEST_SERVER_SERVICE_spec

	var (
		val string
		e   int32
		ok  bool
		err error
		_   = err
	)

	val, ok = pathParams["name"]
	if !ok {
		runtime.RequestHandled(ctx, spec, "StressService", "SayHelloDisabled", nil, &metadata, err)
		return nil, metadata, status.Errorf(codes.InvalidArgument, "missing parameter %s", "name")
	}

	protoReq.Name, err = runtime.String(val)

	if err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "type mismatch, parameter: %s, error: %v", "name", err)
	}

	val, ok = pathParams["gender"]
	if !ok {
		runtime.RequestHandled(ctx, spec, "StressService", "SayHelloDisabled", nil, &metadata, err)
		return nil, metadata, status.Errorf(codes.InvalidArgument, "missing parameter %s", "gender")
	}

	e, err = runtime.Enum(val, Gender_value)

	if err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "type mismatch, parameter: %s, error: %v", "gender", err)
	}

	protoReq.Gender = Gender(e)

	// Only hook up for non-stream call for now.

	runtime.RequestParsed(ctx, spec, "StressService", "SayHelloDisabled", &protoReq, &metadata)
	ctx = runtime.PreLoadBalance(ctx, "ROUND_ROBIN", "", &protoReq)
	msg, err := client.SayHelloDisabled(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	// if err != nil {
	// 	grpclog.Errorf("client.%s returns error: %v", "SayHelloDisabled", err)
	// }
	runtime.RequestHandled(ctx, spec, "StressService", "SayHelloDisabled", msg, &metadata, err)
	return msg, metadata, err

}

func local_request_StressService_SayHelloDisabled_0(ctx context.Context, marshaler runtime.Marshaler, server StressServiceServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq SayHelloReq
	var metadata runtime.ServerMetadata

	var (
		val string
		e   int32
		ok  bool
		err error
		_   = err
	)

	val, ok = pathParams["name"]
	if !ok {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "missing parameter %s", "name")
	}

	protoReq.Name, err = runtime.String(val)

	if err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "type mismatch, parameter: %s, error: %v", "name", err)
	}

	val, ok = pathParams["gender"]
	if !ok {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "missing parameter %s", "gender")
	}

	e, err = runtime.Enum(val, Gender_value)

	if err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "type mismatch, parameter: %s, error: %v", "gender", err)
	}

	protoReq.Gender = Gender(e)

	msg, err := server.SayHelloDisabled(ctx, &protoReq)
	return msg, metadata, err

}

// Register itself to runtime.
func init() {
	var s *runtime.Service
	var spec *skypb.ServiceSpec

	_ = s
	_ = spec

	spec = internal_StressService_SHARED_TEST_SERVER_SERVICE_spec
	s = &runtime.Service{
		Spec:     *spec,
		Name:     "StressService",
		Register: RegisterStressServiceHandlerFromEndpoint,
		Enable:   EnableStressService_Service,
		Disable:  DisableStressService_Service,
	}

	runtime.AddService(s, Enable_SHARED_TEST_SERVER_SERVICE__default__grpc_ServiceGroup, Disable_SHARED_TEST_SERVER_SERVICE__default__grpc_ServiceGroup)

}

// RegisterStressServiceHandlerFromEndpoint is same as RegisterStressServiceHandler but
// automatically dials to "endpoint" and closes the connection when "ctx" gets done.
func RegisterStressServiceHandlerFromEndpoint(mux *runtime.ServeMux) (err error) {
	// conn, err := grpc.Dial(endpoint, opts...)
	// if err != nil {
	// 	return err
	// }
	// defer func() {
	// 	if err != nil {
	// 		if cerr := conn.Close(); cerr != nil {
	// 			grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
	// 		}
	// 		return
	// 	}
	// 	go func() {
	// 		<-ctx.Done()
	// 		if cerr := conn.Close(); cerr != nil {
	// 			grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
	// 		}
	// 	}()
	// }()

	// return RegisterStressServiceHandler(ctx, mux, conn)
	return RegisterStressServiceHandler(nil, mux, nil)
}

// RegisterStressServiceHandler registers the http handlers for service StressService to "mux".
// The handlers forward requests to the grpc endpoint over "conn".
func RegisterStressServiceHandler(ctx context.Context, mux *runtime.ServeMux, conn *grpc.ClientConn) error {
	return RegisterStressServiceHandlerClient(ctx, mux, NewStressServiceClient(conn))
}

// RegisterStressServiceHandlerClient registers the http handlers for service StressService
// to "mux". The handlers forward requests to the grpc endpoint over the given implementation of "StressServiceClient".
// Note: the gRPC framework executes interceptors within the gRPC handler. If the passed in "StressServiceClient"
// doesn't go through the normal gRPC flow (creating a gRPC client etc.) then it will be up to the passed in
// "StressServiceClient" to call the correct interceptors.
func RegisterStressServiceHandlerClient(ctx context.Context, mux *runtime.ServeMux, client StressServiceClient) error {
	spec := internal_StressService_SHARED_TEST_SERVER_SERVICE_spec

	runtime.AddMethod(spec, "StressService", "SayHello", "/stress/v1/say-hello/{name}/gender/{gender}", "GET", true, false, false, "UNSPECIFIED", "EASE_GATEWAY", "EASE_AUTH_TOKEN", "")
	mux.Handle("GET", pattern_StressService_SayHello_0, vexpb.ServiceId_SHARED_TEST_SERVER_SERVICE, func(inctx context.Context, w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		// TODO(mojz): review all locking/unlocking logic.
		// internal_SHARED_TEST_SERVER_SERVICE__default__grpc_lock.RLock()
		// defer internal_SHARED_TEST_SERVER_SERVICE__default__grpc_lock.RUnlock()
		client := internal_StressService_SHARED_TEST_SERVER_SERVICE_client
		if client == nil {
			runtime.DefaultOtherErrorHandler(w, req, "service disabled", http.StatusInternalServerError)
			return
		}

		ctx, err := runtime.RequestAccepted(inctx, internal_StressService_SHARED_TEST_SERVER_SERVICE_spec, "StressService", "SayHello", w, req)
		if err != nil {
			// grpclog.Errorf("runtime.RequestAccepted returns error: %v", err)
			runtime.HTTPError(ctx, nil, &runtime.JSONBuiltin{}, w, req, err)
			return
		}
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		rctx, err := runtime.AnnotateContext(ctx, mux, req)
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_StressService_SayHello_0(rctx, inboundMarshaler, client, req, pathParams)
		ctx = runtime.NewServerMetadataContext(ctx, md)
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_StressService_SayHello_0(ctx, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	runtime.AddMethod(spec, "StressService", "SayHelloDisabled", "/stress/v1/say-hello-disabled/{name}/gender/{gender}", "GET", true, false, false, "UNSPECIFIED", "EASE_GATEWAY", "EASE_AUTH_TOKEN", "")
	mux.Handle("GET", pattern_StressService_SayHelloDisabled_0, vexpb.ServiceId_SHARED_TEST_SERVER_SERVICE, func(inctx context.Context, w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		// TODO(mojz): review all locking/unlocking logic.
		// internal_SHARED_TEST_SERVER_SERVICE__default__grpc_lock.RLock()
		// defer internal_SHARED_TEST_SERVER_SERVICE__default__grpc_lock.RUnlock()
		client := internal_StressService_SHARED_TEST_SERVER_SERVICE_client
		if client == nil {
			runtime.DefaultOtherErrorHandler(w, req, "service disabled", http.StatusInternalServerError)
			return
		}

		ctx, err := runtime.RequestAccepted(inctx, internal_StressService_SHARED_TEST_SERVER_SERVICE_spec, "StressService", "SayHelloDisabled", w, req)
		if err != nil {
			// grpclog.Errorf("runtime.RequestAccepted returns error: %v", err)
			runtime.HTTPError(ctx, nil, &runtime.JSONBuiltin{}, w, req, err)
			return
		}
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		rctx, err := runtime.AnnotateContext(ctx, mux, req)
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_StressService_SayHelloDisabled_0(rctx, inboundMarshaler, client, req, pathParams)
		ctx = runtime.NewServerMetadataContext(ctx, md)
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_StressService_SayHelloDisabled_0(ctx, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	return nil
}

func Disable_SHARED_TEST_SERVER_SERVICE__default__grpc_ServiceGroup() {
	// internal_SHARED_TEST_SERVER_SERVICE__default__grpc_lock.Lock()
	// defer internal_SHARED_TEST_SERVER_SERVICE__default__grpc_lock.Unlock()
	if internal_SHARED_TEST_SERVER_SERVICE__default__grpc_skycli != nil {
		spec := internal_StressService_SHARED_TEST_SERVER_SERVICE_spec
		sg := runtime.GetServiceGroup(spec)
		for _, svc := range sg.Services {
			svc.Disable()
		}

		internal_StressService_SHARED_TEST_SERVER_SERVICE_client = nil
		internal_SHARED_TEST_SERVER_SERVICE__default__grpc_skycli.Shutdown()
		internal_SHARED_TEST_SERVER_SERVICE__default__grpc_skycli = nil
	}
}

func Enable_SHARED_TEST_SERVER_SERVICE__default__grpc_ServiceGroup() {
	// internal_SHARED_TEST_SERVER_SERVICE__default__grpc_lock.Lock()
	// defer internal_SHARED_TEST_SERVER_SERVICE__default__grpc_lock.Unlock()

	internal_SHARED_TEST_SERVER_SERVICE__default__grpc_skycli = client.NewServiceCli(runtime.CallerServiceId)

	// Resolve service
	spec := internal_StressService_SHARED_TEST_SERVER_SERVICE_spec

	internal_SHARED_TEST_SERVER_SERVICE__default__grpc_skycli.Resolve(spec)

	internal_SHARED_TEST_SERVER_SERVICE__default__grpc_skycli.EnableResolveFullEps()
	internal_SHARED_TEST_SERVER_SERVICE__default__grpc_skycli.Start(func(spec *skypb.ServiceSpec, conn *grpc.ClientConn) {
		sg := runtime.GetServiceGroup(spec)
		for _, svc := range sg.Services {
			svc.Enable(spec, conn)
		}
	})
}

func EnableStressService_Service(spec *skypb.ServiceSpec, conn *grpc.ClientConn) {
	internal_StressService_SHARED_TEST_SERVER_SERVICE_client = NewStressServiceClient(conn)
}

func DisableStressService_Service() {
	internal_StressService_SHARED_TEST_SERVER_SERVICE_client = nil
}

var (
	pattern_StressService_SayHello_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1, 2, 2, 1, 0, 4, 1, 5, 3, 2, 4, 1, 0, 4, 1, 5, 4}, []string{"stress", "v1", "say-hello", "name", "gender"}, "", runtime.AssumeColonVerbOpt(true)))

	pattern_StressService_SayHelloDisabled_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1, 2, 2, 1, 0, 4, 1, 5, 3, 2, 4, 1, 0, 4, 1, 5, 4}, []string{"stress", "v1", "say-hello-disabled", "name", "gender"}, "", runtime.AssumeColonVerbOpt(true)))
)

var (
	forward_StressService_SayHello_0 = runtime.ForwardResponseMessage

	forward_StressService_SayHelloDisabled_0 = runtime.ForwardResponseMessage
)

var (
	internal_StressService_SHARED_TEST_SERVER_SERVICE_spec   = client.NewServiceSpec("default", vexpb.ServiceId_SHARED_TEST_SERVER_SERVICE, "grpc")
	internal_StressService_SHARED_TEST_SERVER_SERVICE_client StressServiceClient

	internal_SHARED_TEST_SERVER_SERVICE__default__grpc_skycli client.ServiceCli

	internal_SHARED_TEST_SERVER_SERVICE__default__grpc_lock = sync.RWMutex{}
)
