// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/api.proto

package api

import (
	context "context"
	fmt "fmt"
	data "github.com/binchencoder/gateway-proto/data"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Operation int32

const (
	Operation_Add    Operation = 0
	Operation_Delete Operation = 1
)

var Operation_name = map[int32]string{
	0: "Add",
	1: "Delete",
}

var Operation_value = map[string]int32{
	"Add":    0,
	"Delete": 1,
}

func (x Operation) String() string {
	return proto.EnumName(Operation_name, int32(x))
}

func (Operation) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ecf0878b123623e2, []int{0}
}

type ServiceSpec struct {
	Namespace            string   `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	ServiceName          string   `protobuf:"bytes,2,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	PortName             string   `protobuf:"bytes,3,opt,name=port_name,json=portName,proto3" json:"port_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServiceSpec) Reset()         { *m = ServiceSpec{} }
func (m *ServiceSpec) String() string { return proto.CompactTextString(m) }
func (*ServiceSpec) ProtoMessage()    {}
func (*ServiceSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecf0878b123623e2, []int{0}
}

func (m *ServiceSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceSpec.Unmarshal(m, b)
}
func (m *ServiceSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceSpec.Marshal(b, m, deterministic)
}
func (m *ServiceSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceSpec.Merge(m, src)
}
func (m *ServiceSpec) XXX_Size() int {
	return xxx_messageInfo_ServiceSpec.Size(m)
}
func (m *ServiceSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceSpec.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceSpec proto.InternalMessageInfo

func (m *ServiceSpec) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *ServiceSpec) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

func (m *ServiceSpec) GetPortName() string {
	if m != nil {
		return m.PortName
	}
	return ""
}

type ResolveRequest struct {
	Services             []*ServiceSpec `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	CallerServiceId      data.ServiceId `protobuf:"varint,2,opt,name=callerServiceId,proto3,enum=data.ServiceId" json:"callerServiceId,omitempty"`
	CallerServiceName    string         `protobuf:"bytes,3,opt,name=callerServiceName,proto3" json:"callerServiceName,omitempty"`
	ResolveFullEndpoints bool           `protobuf:"varint,4,opt,name=resolve_full_endpoints,json=resolveFullEndpoints,proto3" json:"resolve_full_endpoints,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ResolveRequest) Reset()         { *m = ResolveRequest{} }
func (m *ResolveRequest) String() string { return proto.CompactTextString(m) }
func (*ResolveRequest) ProtoMessage()    {}
func (*ResolveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecf0878b123623e2, []int{1}
}

func (m *ResolveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResolveRequest.Unmarshal(m, b)
}
func (m *ResolveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResolveRequest.Marshal(b, m, deterministic)
}
func (m *ResolveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResolveRequest.Merge(m, src)
}
func (m *ResolveRequest) XXX_Size() int {
	return xxx_messageInfo_ResolveRequest.Size(m)
}
func (m *ResolveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ResolveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ResolveRequest proto.InternalMessageInfo

func (m *ResolveRequest) GetServices() []*ServiceSpec {
	if m != nil {
		return m.Services
	}
	return nil
}

func (m *ResolveRequest) GetCallerServiceId() data.ServiceId {
	if m != nil {
		return m.CallerServiceId
	}
	return data.ServiceId_SERVICE_NONE
}

func (m *ResolveRequest) GetCallerServiceName() string {
	if m != nil {
		return m.CallerServiceName
	}
	return ""
}

func (m *ResolveRequest) GetResolveFullEndpoints() bool {
	if m != nil {
		return m.ResolveFullEndpoints
	}
	return false
}

type InstanceEndpoint struct {
	Op                   Operation `protobuf:"varint,1,opt,name=op,proto3,enum=api.Operation" json:"op,omitempty"` // Deprecated: Do not use.
	Host                 string    `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Port                 int32     `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	Weight               int32     `protobuf:"varint,4,opt,name=weight,proto3" json:"weight,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *InstanceEndpoint) Reset()         { *m = InstanceEndpoint{} }
func (m *InstanceEndpoint) String() string { return proto.CompactTextString(m) }
func (*InstanceEndpoint) ProtoMessage()    {}
func (*InstanceEndpoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecf0878b123623e2, []int{2}
}

func (m *InstanceEndpoint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstanceEndpoint.Unmarshal(m, b)
}
func (m *InstanceEndpoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstanceEndpoint.Marshal(b, m, deterministic)
}
func (m *InstanceEndpoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstanceEndpoint.Merge(m, src)
}
func (m *InstanceEndpoint) XXX_Size() int {
	return xxx_messageInfo_InstanceEndpoint.Size(m)
}
func (m *InstanceEndpoint) XXX_DiscardUnknown() {
	xxx_messageInfo_InstanceEndpoint.DiscardUnknown(m)
}

var xxx_messageInfo_InstanceEndpoint proto.InternalMessageInfo

// Deprecated: Do not use.
func (m *InstanceEndpoint) GetOp() Operation {
	if m != nil {
		return m.Op
	}
	return Operation_Add
}

func (m *InstanceEndpoint) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *InstanceEndpoint) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *InstanceEndpoint) GetWeight() int32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

type ServiceEndpoints struct {
	Spec                 *ServiceSpec        `protobuf:"bytes,1,opt,name=spec,proto3" json:"spec,omitempty"`
	InstEndpoints        []*InstanceEndpoint `protobuf:"bytes,2,rep,name=inst_endpoints,json=instEndpoints,proto3" json:"inst_endpoints,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ServiceEndpoints) Reset()         { *m = ServiceEndpoints{} }
func (m *ServiceEndpoints) String() string { return proto.CompactTextString(m) }
func (*ServiceEndpoints) ProtoMessage()    {}
func (*ServiceEndpoints) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecf0878b123623e2, []int{3}
}

func (m *ServiceEndpoints) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceEndpoints.Unmarshal(m, b)
}
func (m *ServiceEndpoints) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceEndpoints.Marshal(b, m, deterministic)
}
func (m *ServiceEndpoints) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceEndpoints.Merge(m, src)
}
func (m *ServiceEndpoints) XXX_Size() int {
	return xxx_messageInfo_ServiceEndpoints.Size(m)
}
func (m *ServiceEndpoints) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceEndpoints.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceEndpoints proto.InternalMessageInfo

func (m *ServiceEndpoints) GetSpec() *ServiceSpec {
	if m != nil {
		return m.Spec
	}
	return nil
}

func (m *ServiceEndpoints) GetInstEndpoints() []*InstanceEndpoint {
	if m != nil {
		return m.InstEndpoints
	}
	return nil
}

type ResolveResponse struct {
	SvcEndpoints         *ServiceEndpoints `protobuf:"bytes,1,opt,name=svc_endpoints,json=svcEndpoints,proto3" json:"svc_endpoints,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ResolveResponse) Reset()         { *m = ResolveResponse{} }
func (m *ResolveResponse) String() string { return proto.CompactTextString(m) }
func (*ResolveResponse) ProtoMessage()    {}
func (*ResolveResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecf0878b123623e2, []int{4}
}

func (m *ResolveResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResolveResponse.Unmarshal(m, b)
}
func (m *ResolveResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResolveResponse.Marshal(b, m, deterministic)
}
func (m *ResolveResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResolveResponse.Merge(m, src)
}
func (m *ResolveResponse) XXX_Size() int {
	return xxx_messageInfo_ResolveResponse.Size(m)
}
func (m *ResolveResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ResolveResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ResolveResponse proto.InternalMessageInfo

func (m *ResolveResponse) GetSvcEndpoints() *ServiceEndpoints {
	if m != nil {
		return m.SvcEndpoints
	}
	return nil
}

type ReportLoadRequest struct {
	Spec                 *ServiceSpec `protobuf:"bytes,1,opt,name=spec,proto3" json:"spec,omitempty"`
	Port                 int32        `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Weight               int32        `protobuf:"varint,3,opt,name=weight,proto3" json:"weight,omitempty"`
	FixedHost            string       `protobuf:"bytes,4,opt,name=fixed_host,json=fixedHost,proto3" json:"fixed_host,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ReportLoadRequest) Reset()         { *m = ReportLoadRequest{} }
func (m *ReportLoadRequest) String() string { return proto.CompactTextString(m) }
func (*ReportLoadRequest) ProtoMessage()    {}
func (*ReportLoadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecf0878b123623e2, []int{5}
}

func (m *ReportLoadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReportLoadRequest.Unmarshal(m, b)
}
func (m *ReportLoadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReportLoadRequest.Marshal(b, m, deterministic)
}
func (m *ReportLoadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReportLoadRequest.Merge(m, src)
}
func (m *ReportLoadRequest) XXX_Size() int {
	return xxx_messageInfo_ReportLoadRequest.Size(m)
}
func (m *ReportLoadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReportLoadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReportLoadRequest proto.InternalMessageInfo

func (m *ReportLoadRequest) GetSpec() *ServiceSpec {
	if m != nil {
		return m.Spec
	}
	return nil
}

func (m *ReportLoadRequest) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *ReportLoadRequest) GetWeight() int32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

func (m *ReportLoadRequest) GetFixedHost() string {
	if m != nil {
		return m.FixedHost
	}
	return ""
}

type ReportLoadResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReportLoadResponse) Reset()         { *m = ReportLoadResponse{} }
func (m *ReportLoadResponse) String() string { return proto.CompactTextString(m) }
func (*ReportLoadResponse) ProtoMessage()    {}
func (*ReportLoadResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecf0878b123623e2, []int{6}
}

func (m *ReportLoadResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReportLoadResponse.Unmarshal(m, b)
}
func (m *ReportLoadResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReportLoadResponse.Marshal(b, m, deterministic)
}
func (m *ReportLoadResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReportLoadResponse.Merge(m, src)
}
func (m *ReportLoadResponse) XXX_Size() int {
	return xxx_messageInfo_ReportLoadResponse.Size(m)
}
func (m *ReportLoadResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReportLoadResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReportLoadResponse proto.InternalMessageInfo

type CheckHealthInstruction struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckHealthInstruction) Reset()         { *m = CheckHealthInstruction{} }
func (m *CheckHealthInstruction) String() string { return proto.CompactTextString(m) }
func (*CheckHealthInstruction) ProtoMessage()    {}
func (*CheckHealthInstruction) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecf0878b123623e2, []int{7}
}

func (m *CheckHealthInstruction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckHealthInstruction.Unmarshal(m, b)
}
func (m *CheckHealthInstruction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckHealthInstruction.Marshal(b, m, deterministic)
}
func (m *CheckHealthInstruction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckHealthInstruction.Merge(m, src)
}
func (m *CheckHealthInstruction) XXX_Size() int {
	return xxx_messageInfo_CheckHealthInstruction.Size(m)
}
func (m *CheckHealthInstruction) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckHealthInstruction.DiscardUnknown(m)
}

var xxx_messageInfo_CheckHealthInstruction proto.InternalMessageInfo

type HealthInfo struct {
	Endpoint             string   `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Latency              int32    `protobuf:"varint,2,opt,name=latency,proto3" json:"latency,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HealthInfo) Reset()         { *m = HealthInfo{} }
func (m *HealthInfo) String() string { return proto.CompactTextString(m) }
func (*HealthInfo) ProtoMessage()    {}
func (*HealthInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecf0878b123623e2, []int{8}
}

func (m *HealthInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthInfo.Unmarshal(m, b)
}
func (m *HealthInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthInfo.Marshal(b, m, deterministic)
}
func (m *HealthInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthInfo.Merge(m, src)
}
func (m *HealthInfo) XXX_Size() int {
	return xxx_messageInfo_HealthInfo.Size(m)
}
func (m *HealthInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthInfo.DiscardUnknown(m)
}

var xxx_messageInfo_HealthInfo proto.InternalMessageInfo

func (m *HealthInfo) GetEndpoint() string {
	if m != nil {
		return m.Endpoint
	}
	return ""
}

func (m *HealthInfo) GetLatency() int32 {
	if m != nil {
		return m.Latency
	}
	return 0
}

type CheckHealthResult struct {
	HealthInfo           []*HealthInfo `protobuf:"bytes,1,rep,name=health_info,json=healthInfo,proto3" json:"health_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *CheckHealthResult) Reset()         { *m = CheckHealthResult{} }
func (m *CheckHealthResult) String() string { return proto.CompactTextString(m) }
func (*CheckHealthResult) ProtoMessage()    {}
func (*CheckHealthResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecf0878b123623e2, []int{9}
}

func (m *CheckHealthResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckHealthResult.Unmarshal(m, b)
}
func (m *CheckHealthResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckHealthResult.Marshal(b, m, deterministic)
}
func (m *CheckHealthResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckHealthResult.Merge(m, src)
}
func (m *CheckHealthResult) XXX_Size() int {
	return xxx_messageInfo_CheckHealthResult.Size(m)
}
func (m *CheckHealthResult) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckHealthResult.DiscardUnknown(m)
}

var xxx_messageInfo_CheckHealthResult proto.InternalMessageInfo

func (m *CheckHealthResult) GetHealthInfo() []*HealthInfo {
	if m != nil {
		return m.HealthInfo
	}
	return nil
}

type FetchInstancesInstruction struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FetchInstancesInstruction) Reset()         { *m = FetchInstancesInstruction{} }
func (m *FetchInstancesInstruction) String() string { return proto.CompactTextString(m) }
func (*FetchInstancesInstruction) ProtoMessage()    {}
func (*FetchInstancesInstruction) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecf0878b123623e2, []int{10}
}

func (m *FetchInstancesInstruction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchInstancesInstruction.Unmarshal(m, b)
}
func (m *FetchInstancesInstruction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchInstancesInstruction.Marshal(b, m, deterministic)
}
func (m *FetchInstancesInstruction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchInstancesInstruction.Merge(m, src)
}
func (m *FetchInstancesInstruction) XXX_Size() int {
	return xxx_messageInfo_FetchInstancesInstruction.Size(m)
}
func (m *FetchInstancesInstruction) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchInstancesInstruction.DiscardUnknown(m)
}

var xxx_messageInfo_FetchInstancesInstruction proto.InternalMessageInfo

type FetchInstancesResult struct {
	SvcEndpoints         *ServiceEndpoints `protobuf:"bytes,1,opt,name=svc_endpoints,json=svcEndpoints,proto3" json:"svc_endpoints,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *FetchInstancesResult) Reset()         { *m = FetchInstancesResult{} }
func (m *FetchInstancesResult) String() string { return proto.CompactTextString(m) }
func (*FetchInstancesResult) ProtoMessage()    {}
func (*FetchInstancesResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecf0878b123623e2, []int{11}
}

func (m *FetchInstancesResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchInstancesResult.Unmarshal(m, b)
}
func (m *FetchInstancesResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchInstancesResult.Marshal(b, m, deterministic)
}
func (m *FetchInstancesResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchInstancesResult.Merge(m, src)
}
func (m *FetchInstancesResult) XXX_Size() int {
	return xxx_messageInfo_FetchInstancesResult.Size(m)
}
func (m *FetchInstancesResult) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchInstancesResult.DiscardUnknown(m)
}

var xxx_messageInfo_FetchInstancesResult proto.InternalMessageInfo

func (m *FetchInstancesResult) GetSvcEndpoints() *ServiceEndpoints {
	if m != nil {
		return m.SvcEndpoints
	}
	return nil
}

type AddInstanceInstruction struct {
	SvcEndpoints         *ServiceEndpoints `protobuf:"bytes,1,opt,name=svc_endpoints,json=svcEndpoints,proto3" json:"svc_endpoints,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *AddInstanceInstruction) Reset()         { *m = AddInstanceInstruction{} }
func (m *AddInstanceInstruction) String() string { return proto.CompactTextString(m) }
func (*AddInstanceInstruction) ProtoMessage()    {}
func (*AddInstanceInstruction) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecf0878b123623e2, []int{12}
}

func (m *AddInstanceInstruction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddInstanceInstruction.Unmarshal(m, b)
}
func (m *AddInstanceInstruction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddInstanceInstruction.Marshal(b, m, deterministic)
}
func (m *AddInstanceInstruction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddInstanceInstruction.Merge(m, src)
}
func (m *AddInstanceInstruction) XXX_Size() int {
	return xxx_messageInfo_AddInstanceInstruction.Size(m)
}
func (m *AddInstanceInstruction) XXX_DiscardUnknown() {
	xxx_messageInfo_AddInstanceInstruction.DiscardUnknown(m)
}

var xxx_messageInfo_AddInstanceInstruction proto.InternalMessageInfo

func (m *AddInstanceInstruction) GetSvcEndpoints() *ServiceEndpoints {
	if m != nil {
		return m.SvcEndpoints
	}
	return nil
}

type AddInstanceResult struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddInstanceResult) Reset()         { *m = AddInstanceResult{} }
func (m *AddInstanceResult) String() string { return proto.CompactTextString(m) }
func (*AddInstanceResult) ProtoMessage()    {}
func (*AddInstanceResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecf0878b123623e2, []int{13}
}

func (m *AddInstanceResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddInstanceResult.Unmarshal(m, b)
}
func (m *AddInstanceResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddInstanceResult.Marshal(b, m, deterministic)
}
func (m *AddInstanceResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddInstanceResult.Merge(m, src)
}
func (m *AddInstanceResult) XXX_Size() int {
	return xxx_messageInfo_AddInstanceResult.Size(m)
}
func (m *AddInstanceResult) XXX_DiscardUnknown() {
	xxx_messageInfo_AddInstanceResult.DiscardUnknown(m)
}

var xxx_messageInfo_AddInstanceResult proto.InternalMessageInfo

type DeleteInstanceInstruction struct {
	SvcEndpoints         *ServiceEndpoints `protobuf:"bytes,1,opt,name=svc_endpoints,json=svcEndpoints,proto3" json:"svc_endpoints,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *DeleteInstanceInstruction) Reset()         { *m = DeleteInstanceInstruction{} }
func (m *DeleteInstanceInstruction) String() string { return proto.CompactTextString(m) }
func (*DeleteInstanceInstruction) ProtoMessage()    {}
func (*DeleteInstanceInstruction) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecf0878b123623e2, []int{14}
}

func (m *DeleteInstanceInstruction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteInstanceInstruction.Unmarshal(m, b)
}
func (m *DeleteInstanceInstruction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteInstanceInstruction.Marshal(b, m, deterministic)
}
func (m *DeleteInstanceInstruction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteInstanceInstruction.Merge(m, src)
}
func (m *DeleteInstanceInstruction) XXX_Size() int {
	return xxx_messageInfo_DeleteInstanceInstruction.Size(m)
}
func (m *DeleteInstanceInstruction) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteInstanceInstruction.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteInstanceInstruction proto.InternalMessageInfo

func (m *DeleteInstanceInstruction) GetSvcEndpoints() *ServiceEndpoints {
	if m != nil {
		return m.SvcEndpoints
	}
	return nil
}

type DeleteInstanceResult struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteInstanceResult) Reset()         { *m = DeleteInstanceResult{} }
func (m *DeleteInstanceResult) String() string { return proto.CompactTextString(m) }
func (*DeleteInstanceResult) ProtoMessage()    {}
func (*DeleteInstanceResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecf0878b123623e2, []int{15}
}

func (m *DeleteInstanceResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteInstanceResult.Unmarshal(m, b)
}
func (m *DeleteInstanceResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteInstanceResult.Marshal(b, m, deterministic)
}
func (m *DeleteInstanceResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteInstanceResult.Merge(m, src)
}
func (m *DeleteInstanceResult) XXX_Size() int {
	return xxx_messageInfo_DeleteInstanceResult.Size(m)
}
func (m *DeleteInstanceResult) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteInstanceResult.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteInstanceResult proto.InternalMessageInfo

type DiagnoseRequest struct {
	// Types that are valid to be assigned to Instruction:
	//	*DiagnoseRequest_CheckHealth
	//	*DiagnoseRequest_FetchInstances
	//	*DiagnoseRequest_AddInstance
	//	*DiagnoseRequest_DeleteInstance
	Instruction          isDiagnoseRequest_Instruction `protobuf_oneof:"instruction"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *DiagnoseRequest) Reset()         { *m = DiagnoseRequest{} }
func (m *DiagnoseRequest) String() string { return proto.CompactTextString(m) }
func (*DiagnoseRequest) ProtoMessage()    {}
func (*DiagnoseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecf0878b123623e2, []int{16}
}

func (m *DiagnoseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiagnoseRequest.Unmarshal(m, b)
}
func (m *DiagnoseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiagnoseRequest.Marshal(b, m, deterministic)
}
func (m *DiagnoseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiagnoseRequest.Merge(m, src)
}
func (m *DiagnoseRequest) XXX_Size() int {
	return xxx_messageInfo_DiagnoseRequest.Size(m)
}
func (m *DiagnoseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DiagnoseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DiagnoseRequest proto.InternalMessageInfo

type isDiagnoseRequest_Instruction interface {
	isDiagnoseRequest_Instruction()
}

type DiagnoseRequest_CheckHealth struct {
	CheckHealth *CheckHealthInstruction `protobuf:"bytes,1,opt,name=check_health,json=checkHealth,proto3,oneof"`
}

type DiagnoseRequest_FetchInstances struct {
	FetchInstances *FetchInstancesInstruction `protobuf:"bytes,2,opt,name=fetch_instances,json=fetchInstances,proto3,oneof"`
}

type DiagnoseRequest_AddInstance struct {
	AddInstance *AddInstanceInstruction `protobuf:"bytes,3,opt,name=add_instance,json=addInstance,proto3,oneof"`
}

type DiagnoseRequest_DeleteInstance struct {
	DeleteInstance *DeleteInstanceInstruction `protobuf:"bytes,4,opt,name=delete_instance,json=deleteInstance,proto3,oneof"`
}

func (*DiagnoseRequest_CheckHealth) isDiagnoseRequest_Instruction() {}

func (*DiagnoseRequest_FetchInstances) isDiagnoseRequest_Instruction() {}

func (*DiagnoseRequest_AddInstance) isDiagnoseRequest_Instruction() {}

func (*DiagnoseRequest_DeleteInstance) isDiagnoseRequest_Instruction() {}

func (m *DiagnoseRequest) GetInstruction() isDiagnoseRequest_Instruction {
	if m != nil {
		return m.Instruction
	}
	return nil
}

func (m *DiagnoseRequest) GetCheckHealth() *CheckHealthInstruction {
	if x, ok := m.GetInstruction().(*DiagnoseRequest_CheckHealth); ok {
		return x.CheckHealth
	}
	return nil
}

func (m *DiagnoseRequest) GetFetchInstances() *FetchInstancesInstruction {
	if x, ok := m.GetInstruction().(*DiagnoseRequest_FetchInstances); ok {
		return x.FetchInstances
	}
	return nil
}

func (m *DiagnoseRequest) GetAddInstance() *AddInstanceInstruction {
	if x, ok := m.GetInstruction().(*DiagnoseRequest_AddInstance); ok {
		return x.AddInstance
	}
	return nil
}

func (m *DiagnoseRequest) GetDeleteInstance() *DeleteInstanceInstruction {
	if x, ok := m.GetInstruction().(*DiagnoseRequest_DeleteInstance); ok {
		return x.DeleteInstance
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*DiagnoseRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*DiagnoseRequest_CheckHealth)(nil),
		(*DiagnoseRequest_FetchInstances)(nil),
		(*DiagnoseRequest_AddInstance)(nil),
		(*DiagnoseRequest_DeleteInstance)(nil),
	}
}

type DiagnoseResponse struct {
	// Types that are valid to be assigned to Result:
	//	*DiagnoseResponse_CheckHealth
	//	*DiagnoseResponse_FetchInstances
	//	*DiagnoseResponse_AddInstance
	//	*DiagnoseResponse_DeleteInstance
	Result               isDiagnoseResponse_Result `protobuf_oneof:"result"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *DiagnoseResponse) Reset()         { *m = DiagnoseResponse{} }
func (m *DiagnoseResponse) String() string { return proto.CompactTextString(m) }
func (*DiagnoseResponse) ProtoMessage()    {}
func (*DiagnoseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecf0878b123623e2, []int{17}
}

func (m *DiagnoseResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiagnoseResponse.Unmarshal(m, b)
}
func (m *DiagnoseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiagnoseResponse.Marshal(b, m, deterministic)
}
func (m *DiagnoseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiagnoseResponse.Merge(m, src)
}
func (m *DiagnoseResponse) XXX_Size() int {
	return xxx_messageInfo_DiagnoseResponse.Size(m)
}
func (m *DiagnoseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DiagnoseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DiagnoseResponse proto.InternalMessageInfo

type isDiagnoseResponse_Result interface {
	isDiagnoseResponse_Result()
}

type DiagnoseResponse_CheckHealth struct {
	CheckHealth *CheckHealthResult `protobuf:"bytes,1,opt,name=check_health,json=checkHealth,proto3,oneof"`
}

type DiagnoseResponse_FetchInstances struct {
	FetchInstances *FetchInstancesResult `protobuf:"bytes,2,opt,name=fetch_instances,json=fetchInstances,proto3,oneof"`
}

type DiagnoseResponse_AddInstance struct {
	AddInstance *AddInstanceResult `protobuf:"bytes,3,opt,name=add_instance,json=addInstance,proto3,oneof"`
}

type DiagnoseResponse_DeleteInstance struct {
	DeleteInstance *DeleteInstanceResult `protobuf:"bytes,4,opt,name=delete_instance,json=deleteInstance,proto3,oneof"`
}

func (*DiagnoseResponse_CheckHealth) isDiagnoseResponse_Result() {}

func (*DiagnoseResponse_FetchInstances) isDiagnoseResponse_Result() {}

func (*DiagnoseResponse_AddInstance) isDiagnoseResponse_Result() {}

func (*DiagnoseResponse_DeleteInstance) isDiagnoseResponse_Result() {}

func (m *DiagnoseResponse) GetResult() isDiagnoseResponse_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *DiagnoseResponse) GetCheckHealth() *CheckHealthResult {
	if x, ok := m.GetResult().(*DiagnoseResponse_CheckHealth); ok {
		return x.CheckHealth
	}
	return nil
}

func (m *DiagnoseResponse) GetFetchInstances() *FetchInstancesResult {
	if x, ok := m.GetResult().(*DiagnoseResponse_FetchInstances); ok {
		return x.FetchInstances
	}
	return nil
}

func (m *DiagnoseResponse) GetAddInstance() *AddInstanceResult {
	if x, ok := m.GetResult().(*DiagnoseResponse_AddInstance); ok {
		return x.AddInstance
	}
	return nil
}

func (m *DiagnoseResponse) GetDeleteInstance() *DeleteInstanceResult {
	if x, ok := m.GetResult().(*DiagnoseResponse_DeleteInstance); ok {
		return x.DeleteInstance
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*DiagnoseResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*DiagnoseResponse_CheckHealth)(nil),
		(*DiagnoseResponse_FetchInstances)(nil),
		(*DiagnoseResponse_AddInstance)(nil),
		(*DiagnoseResponse_DeleteInstance)(nil),
	}
}

func init() {
	proto.RegisterEnum("api.Operation", Operation_name, Operation_value)
	proto.RegisterType((*ServiceSpec)(nil), "api.ServiceSpec")
	proto.RegisterType((*ResolveRequest)(nil), "api.ResolveRequest")
	proto.RegisterType((*InstanceEndpoint)(nil), "api.InstanceEndpoint")
	proto.RegisterType((*ServiceEndpoints)(nil), "api.ServiceEndpoints")
	proto.RegisterType((*ResolveResponse)(nil), "api.ResolveResponse")
	proto.RegisterType((*ReportLoadRequest)(nil), "api.ReportLoadRequest")
	proto.RegisterType((*ReportLoadResponse)(nil), "api.ReportLoadResponse")
	proto.RegisterType((*CheckHealthInstruction)(nil), "api.CheckHealthInstruction")
	proto.RegisterType((*HealthInfo)(nil), "api.HealthInfo")
	proto.RegisterType((*CheckHealthResult)(nil), "api.CheckHealthResult")
	proto.RegisterType((*FetchInstancesInstruction)(nil), "api.FetchInstancesInstruction")
	proto.RegisterType((*FetchInstancesResult)(nil), "api.FetchInstancesResult")
	proto.RegisterType((*AddInstanceInstruction)(nil), "api.AddInstanceInstruction")
	proto.RegisterType((*AddInstanceResult)(nil), "api.AddInstanceResult")
	proto.RegisterType((*DeleteInstanceInstruction)(nil), "api.DeleteInstanceInstruction")
	proto.RegisterType((*DeleteInstanceResult)(nil), "api.DeleteInstanceResult")
	proto.RegisterType((*DiagnoseRequest)(nil), "api.DiagnoseRequest")
	proto.RegisterType((*DiagnoseResponse)(nil), "api.DiagnoseResponse")
}

func init() { proto.RegisterFile("proto/api.proto", fileDescriptor_ecf0878b123623e2) }

var fileDescriptor_ecf0878b123623e2 = []byte{
	// 865 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0xdd, 0x6e, 0xe3, 0x44,
	0x14, 0xae, 0x9d, 0xb4, 0x4d, 0x4f, 0xda, 0x38, 0x9d, 0xcd, 0x9a, 0xb4, 0x5d, 0x50, 0xb0, 0xb8,
	0x88, 0xd0, 0x2a, 0x5b, 0x05, 0x84, 0x04, 0x8b, 0x04, 0xcd, 0xa6, 0x55, 0x2a, 0xc1, 0xb2, 0x9a,
	0x22, 0x71, 0x19, 0x4d, 0xc7, 0x93, 0xb5, 0x55, 0xd7, 0x63, 0x3c, 0x93, 0xc0, 0xde, 0xf3, 0x24,
	0x3c, 0x06, 0x2f, 0xc0, 0x53, 0xf0, 0x2e, 0x68, 0xc6, 0xe3, 0x9f, 0x78, 0x1d, 0x09, 0x69, 0xb9,
	0xa9, 0x66, 0xce, 0x77, 0xfa, 0x9d, 0xef, 0x7c, 0x67, 0x66, 0x1c, 0x70, 0x92, 0x94, 0x4b, 0xfe,
	0x82, 0x24, 0xe1, 0x44, 0xaf, 0x50, 0x8b, 0x24, 0xe1, 0xb9, 0xe3, 0x13, 0x49, 0x5e, 0xa8, 0x3f,
	0x59, 0xd4, 0x7b, 0x80, 0xee, 0x1d, 0x4b, 0x37, 0x21, 0x65, 0x77, 0x09, 0xa3, 0xe8, 0x19, 0x1c,
	0xc5, 0xe4, 0x91, 0x89, 0x84, 0x50, 0x36, 0xb4, 0x46, 0xd6, 0xf8, 0x08, 0x97, 0x01, 0xf4, 0x29,
	0x1c, 0x8b, 0x2c, 0x79, 0xa9, 0x82, 0x43, 0x5b, 0x27, 0x74, 0x4d, 0xec, 0x35, 0x79, 0x64, 0xe8,
	0x02, 0x8e, 0x12, 0x9e, 0xca, 0x0c, 0x6f, 0x69, 0xbc, 0xa3, 0x02, 0x0a, 0xf4, 0xfe, 0xb1, 0xa0,
	0x87, 0x99, 0xe0, 0xd1, 0x86, 0x61, 0xf6, 0xeb, 0x9a, 0x09, 0x89, 0x9e, 0x43, 0xc7, 0xfc, 0xbb,
	0x18, 0x5a, 0xa3, 0xd6, 0xb8, 0x3b, 0xed, 0x4f, 0x94, 0xe6, 0x8a, 0x28, 0x5c, 0x64, 0xa0, 0xaf,
	0xc1, 0xa1, 0x24, 0x8a, 0x58, 0x6a, 0xe0, 0x5b, 0x5f, 0x6b, 0xe8, 0x4d, 0x9d, 0x89, 0xee, 0xa9,
	0x08, 0xe3, 0x7a, 0x1e, 0x7a, 0x0e, 0xa7, 0x5b, 0xa1, 0xd7, 0xa5, 0xc0, 0xf7, 0x01, 0xf4, 0x25,
	0xb8, 0x69, 0x26, 0x74, 0xb9, 0x5a, 0x47, 0xd1, 0x92, 0xc5, 0x7e, 0xc2, 0xc3, 0x58, 0x8a, 0x61,
	0x7b, 0x64, 0x8d, 0x3b, 0x78, 0x60, 0xd0, 0x9b, 0x75, 0x14, 0x5d, 0xe7, 0x98, 0xb7, 0x81, 0xfe,
	0x6d, 0x2c, 0x24, 0x89, 0x29, 0xcb, 0x83, 0xc8, 0x03, 0x9b, 0x27, 0xda, 0xca, 0xde, 0xb4, 0xa7,
	0x5b, 0xfb, 0x29, 0x61, 0x29, 0x91, 0x21, 0x8f, 0x67, 0xf6, 0xd0, 0xc2, 0x36, 0x4f, 0x10, 0x82,
	0x76, 0xc0, 0x85, 0x34, 0x7e, 0xea, 0xb5, 0x8a, 0x29, 0xdf, 0xb4, 0xc4, 0x7d, 0xac, 0xd7, 0xc8,
	0x85, 0x83, 0xdf, 0x58, 0xf8, 0x36, 0x90, 0x5a, 0xc5, 0x3e, 0x36, 0x3b, 0x55, 0xd7, 0x88, 0x2f,
	0xb4, 0xa0, 0xcf, 0xa0, 0x2d, 0x12, 0x46, 0x75, 0xe5, 0x26, 0x53, 0x35, 0x8a, 0xbe, 0x85, 0x5e,
	0x18, 0x0b, 0x59, 0xe9, 0xcf, 0xd6, 0x43, 0x78, 0xaa, 0xf3, 0xeb, 0xcd, 0xe0, 0x13, 0x95, 0x5c,
	0xf6, 0xfb, 0x23, 0x38, 0xc5, 0x38, 0x45, 0xc2, 0x63, 0xc1, 0xd0, 0x37, 0x70, 0x22, 0x36, 0xb4,
	0xc2, 0x97, 0xd5, 0x7f, 0x5a, 0xad, 0x5f, 0x10, 0xe0, 0x63, 0xb1, 0xa1, 0x25, 0xdd, 0x1f, 0x16,
	0x9c, 0x62, 0xa6, 0x3a, 0xfd, 0x81, 0x13, 0x3f, 0x3f, 0x21, 0xff, 0xad, 0x91, 0xdc, 0x2e, 0xbb,
	0xd1, 0xae, 0x56, 0xd5, 0x2e, 0xf4, 0x31, 0xc0, 0x2a, 0xfc, 0x9d, 0xf9, 0x4b, 0x6d, 0x7a, 0x3b,
	0x3b, 0xe5, 0x3a, 0xb2, 0xe0, 0x42, 0x7a, 0x03, 0x40, 0x55, 0x15, 0x59, 0x63, 0xde, 0x10, 0xdc,
	0x57, 0x01, 0xa3, 0x0f, 0x0b, 0x46, 0x22, 0x19, 0x28, 0x67, 0xd2, 0x35, 0x55, 0x53, 0xf4, 0x66,
	0x00, 0x79, 0x70, 0xc5, 0xd1, 0x39, 0x74, 0xf2, 0xe6, 0xcd, 0x05, 0x2a, 0xf6, 0x68, 0x08, 0x87,
	0x11, 0x91, 0x2c, 0xa6, 0xef, 0x8c, 0xce, 0x7c, 0xeb, 0x5d, 0xc3, 0x69, 0x85, 0x1d, 0x33, 0xb1,
	0x8e, 0x24, 0xba, 0x84, 0x6e, 0xa0, 0xf7, 0xcb, 0x30, 0x5e, 0x71, 0x73, 0x3d, 0x1c, 0x6d, 0x40,
	0x59, 0x10, 0x43, 0x50, 0xac, 0xbd, 0x0b, 0x38, 0xbb, 0x61, 0x92, 0x06, 0xf9, 0xe0, 0x44, 0x55,
	0x27, 0x86, 0xc1, 0x36, 0x68, 0xca, 0x7c, 0xc8, 0xc8, 0x7e, 0x06, 0xf7, 0xca, 0xf7, 0x73, 0xc6,
	0x4a, 0xb5, 0x0f, 0x62, 0x7d, 0x02, 0xa7, 0x15, 0xd6, 0x4c, 0xa6, 0xf7, 0x0b, 0x9c, 0xcd, 0x59,
	0xc4, 0x24, 0xfb, 0xbf, 0xab, 0xb9, 0x30, 0xd8, 0x26, 0x36, 0x05, 0xff, 0xb2, 0xc1, 0x99, 0x87,
	0xe4, 0x6d, 0xcc, 0x45, 0xf1, 0x5c, 0x7d, 0x0f, 0xc7, 0x54, 0xcd, 0x69, 0x99, 0x99, 0x6e, 0xca,
	0x5c, 0xe8, 0x32, 0xcd, 0xc7, 0x63, 0xb1, 0x87, 0xbb, 0xb4, 0x44, 0xd0, 0x2d, 0x38, 0x2b, 0x35,
	0x85, 0x65, 0x98, 0x8f, 0x41, 0x9f, 0x85, 0xee, 0xf4, 0x13, 0x4d, 0xb2, 0x73, 0x7c, 0x8b, 0x3d,
	0xdc, 0x5b, 0x6d, 0x81, 0x4a, 0x0c, 0xf1, 0xfd, 0x82, 0x48, 0x9f, 0xf2, 0x5c, 0x4c, 0xf3, 0x54,
	0x94, 0x18, 0x52, 0x22, 0x4a, 0x8c, 0xaf, 0x5b, 0x2f, 0x49, 0xda, 0x15, 0x31, 0x3b, 0xfd, 0x56,
	0x62, 0xfc, 0x2d, 0x70, 0x76, 0x02, 0xdd, 0xb0, 0x72, 0xd8, 0xfe, 0xb4, 0xa1, 0x5f, 0x9a, 0x67,
	0x1e, 0x87, 0x97, 0x8d, 0xee, 0xb9, 0x75, 0xf7, 0x32, 0xff, 0xeb, 0xc6, 0xcd, 0x77, 0x19, 0x77,
	0xd6, 0x60, 0x5c, 0x41, 0x51, 0xf7, 0xec, 0x65, 0xa3, 0x67, 0x6e, 0xdd, 0xb3, 0x52, 0x42, 0xd5,
	0xae, 0xf9, 0x2e, 0xbb, 0xce, 0x1a, 0xec, 0x2a, 0x25, 0xd4, 0x9c, 0xea, 0xc0, 0x41, 0xaa, 0xb1,
	0xcf, 0x47, 0x70, 0x54, 0x7c, 0x0c, 0xd0, 0x21, 0xb4, 0xae, 0x7c, 0xbf, 0xbf, 0x87, 0x00, 0x0e,
	0x32, 0xa6, 0xbe, 0x35, 0xfd, 0xdb, 0x82, 0xfd, 0xbb, 0x87, 0x77, 0xd1, 0x3d, 0xfa, 0x0a, 0x0e,
	0xcd, 0x5b, 0x8b, 0x9e, 0xe8, 0x6a, 0xdb, 0x1f, 0xd2, 0xf3, 0xc1, 0x76, 0x30, 0x73, 0xfc, 0xd2,
	0x42, 0xdf, 0x01, 0x94, 0xaf, 0x19, 0x72, 0x4d, 0x56, 0xed, 0x91, 0x3d, 0xff, 0xe8, 0xbd, 0x78,
	0x46, 0x30, 0xb6, 0xd0, 0x35, 0xa0, 0x2b, 0x29, 0x09, 0x0d, 0x6e, 0x78, 0x6a, 0x26, 0x1a, 0x0a,
	0x94, 0xdd, 0xac, 0xfa, 0x84, 0x8d, 0x8a, 0xda, 0xad, 0x19, 0x5b, 0x97, 0xd6, 0x6c, 0x02, 0xcf,
	0x28, 0x7f, 0x9c, 0xdc, 0x87, 0x31, 0x0d, 0x58, 0x4c, 0xb9, 0xcf, 0xd2, 0x89, 0x50, 0x9d, 0x65,
	0x3f, 0x44, 0x66, 0xc7, 0xaf, 0xa2, 0x90, 0xc5, 0xf2, 0x8d, 0xda, 0x88, 0x37, 0x7b, 0xf7, 0x07,
	0x3a, 0xfc, 0xc5, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x2d, 0x48, 0xaa, 0x9c, 0xc8, 0x08, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// SkylbClient is the client API for Skylb service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SkylbClient interface {
	Resolve(ctx context.Context, in *ResolveRequest, opts ...grpc.CallOption) (Skylb_ResolveClient, error)
	ReportLoad(ctx context.Context, opts ...grpc.CallOption) (Skylb_ReportLoadClient, error)
	AttachForDiagnosis(ctx context.Context, opts ...grpc.CallOption) (Skylb_AttachForDiagnosisClient, error)
}

type skylbClient struct {
	cc grpc.ClientConnInterface
}

func NewSkylbClient(cc grpc.ClientConnInterface) SkylbClient {
	return &skylbClient{cc}
}

func (c *skylbClient) Resolve(ctx context.Context, in *ResolveRequest, opts ...grpc.CallOption) (Skylb_ResolveClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Skylb_serviceDesc.Streams[0], "/api.Skylb/Resolve", opts...)
	if err != nil {
		return nil, err
	}
	x := &skylbResolveClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Skylb_ResolveClient interface {
	Recv() (*ResolveResponse, error)
	grpc.ClientStream
}

type skylbResolveClient struct {
	grpc.ClientStream
}

func (x *skylbResolveClient) Recv() (*ResolveResponse, error) {
	m := new(ResolveResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *skylbClient) ReportLoad(ctx context.Context, opts ...grpc.CallOption) (Skylb_ReportLoadClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Skylb_serviceDesc.Streams[1], "/api.Skylb/ReportLoad", opts...)
	if err != nil {
		return nil, err
	}
	x := &skylbReportLoadClient{stream}
	return x, nil
}

type Skylb_ReportLoadClient interface {
	Send(*ReportLoadRequest) error
	CloseAndRecv() (*ReportLoadResponse, error)
	grpc.ClientStream
}

type skylbReportLoadClient struct {
	grpc.ClientStream
}

func (x *skylbReportLoadClient) Send(m *ReportLoadRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *skylbReportLoadClient) CloseAndRecv() (*ReportLoadResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(ReportLoadResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *skylbClient) AttachForDiagnosis(ctx context.Context, opts ...grpc.CallOption) (Skylb_AttachForDiagnosisClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Skylb_serviceDesc.Streams[2], "/api.Skylb/AttachForDiagnosis", opts...)
	if err != nil {
		return nil, err
	}
	x := &skylbAttachForDiagnosisClient{stream}
	return x, nil
}

type Skylb_AttachForDiagnosisClient interface {
	Send(*DiagnoseResponse) error
	Recv() (*DiagnoseRequest, error)
	grpc.ClientStream
}

type skylbAttachForDiagnosisClient struct {
	grpc.ClientStream
}

func (x *skylbAttachForDiagnosisClient) Send(m *DiagnoseResponse) error {
	return x.ClientStream.SendMsg(m)
}

func (x *skylbAttachForDiagnosisClient) Recv() (*DiagnoseRequest, error) {
	m := new(DiagnoseRequest)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SkylbServer is the server API for Skylb service.
type SkylbServer interface {
	Resolve(*ResolveRequest, Skylb_ResolveServer) error
	ReportLoad(Skylb_ReportLoadServer) error
	AttachForDiagnosis(Skylb_AttachForDiagnosisServer) error
}

// UnimplementedSkylbServer can be embedded to have forward compatible implementations.
type UnimplementedSkylbServer struct {
}

func (*UnimplementedSkylbServer) Resolve(req *ResolveRequest, srv Skylb_ResolveServer) error {
	return status.Errorf(codes.Unimplemented, "method Resolve not implemented")
}
func (*UnimplementedSkylbServer) ReportLoad(srv Skylb_ReportLoadServer) error {
	return status.Errorf(codes.Unimplemented, "method ReportLoad not implemented")
}
func (*UnimplementedSkylbServer) AttachForDiagnosis(srv Skylb_AttachForDiagnosisServer) error {
	return status.Errorf(codes.Unimplemented, "method AttachForDiagnosis not implemented")
}

func RegisterSkylbServer(s *grpc.Server, srv SkylbServer) {
	s.RegisterService(&_Skylb_serviceDesc, srv)
}

func _Skylb_Resolve_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ResolveRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SkylbServer).Resolve(m, &skylbResolveServer{stream})
}

type Skylb_ResolveServer interface {
	Send(*ResolveResponse) error
	grpc.ServerStream
}

type skylbResolveServer struct {
	grpc.ServerStream
}

func (x *skylbResolveServer) Send(m *ResolveResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Skylb_ReportLoad_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SkylbServer).ReportLoad(&skylbReportLoadServer{stream})
}

type Skylb_ReportLoadServer interface {
	SendAndClose(*ReportLoadResponse) error
	Recv() (*ReportLoadRequest, error)
	grpc.ServerStream
}

type skylbReportLoadServer struct {
	grpc.ServerStream
}

func (x *skylbReportLoadServer) SendAndClose(m *ReportLoadResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *skylbReportLoadServer) Recv() (*ReportLoadRequest, error) {
	m := new(ReportLoadRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Skylb_AttachForDiagnosis_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SkylbServer).AttachForDiagnosis(&skylbAttachForDiagnosisServer{stream})
}

type Skylb_AttachForDiagnosisServer interface {
	Send(*DiagnoseRequest) error
	Recv() (*DiagnoseResponse, error)
	grpc.ServerStream
}

type skylbAttachForDiagnosisServer struct {
	grpc.ServerStream
}

func (x *skylbAttachForDiagnosisServer) Send(m *DiagnoseRequest) error {
	return x.ServerStream.SendMsg(m)
}

func (x *skylbAttachForDiagnosisServer) Recv() (*DiagnoseResponse, error) {
	m := new(DiagnoseResponse)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Skylb_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Skylb",
	HandlerType: (*SkylbServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Resolve",
			Handler:       _Skylb_Resolve_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ReportLoad",
			Handler:       _Skylb_ReportLoad_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "AttachForDiagnosis",
			Handler:       _Skylb_AttachForDiagnosis_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/api.proto",
}
