// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cmd/mainservice-demo/proto/api.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AutoSelectRequest struct {
	From                 string   `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AutoSelectRequest) Reset()         { *m = AutoSelectRequest{} }
func (m *AutoSelectRequest) String() string { return proto.CompactTextString(m) }
func (*AutoSelectRequest) ProtoMessage()    {}
func (*AutoSelectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_46953b6d0e9afa48, []int{0}
}

func (m *AutoSelectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AutoSelectRequest.Unmarshal(m, b)
}
func (m *AutoSelectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AutoSelectRequest.Marshal(b, m, deterministic)
}
func (m *AutoSelectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AutoSelectRequest.Merge(m, src)
}
func (m *AutoSelectRequest) XXX_Size() int {
	return xxx_messageInfo_AutoSelectRequest.Size(m)
}
func (m *AutoSelectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AutoSelectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AutoSelectRequest proto.InternalMessageInfo

func (m *AutoSelectRequest) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

type AutoSelectResponse struct {
	Server               string   `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AutoSelectResponse) Reset()         { *m = AutoSelectResponse{} }
func (m *AutoSelectResponse) String() string { return proto.CompactTextString(m) }
func (*AutoSelectResponse) ProtoMessage()    {}
func (*AutoSelectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_46953b6d0e9afa48, []int{1}
}

func (m *AutoSelectResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AutoSelectResponse.Unmarshal(m, b)
}
func (m *AutoSelectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AutoSelectResponse.Marshal(b, m, deterministic)
}
func (m *AutoSelectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AutoSelectResponse.Merge(m, src)
}
func (m *AutoSelectResponse) XXX_Size() int {
	return xxx_messageInfo_AutoSelectResponse.Size(m)
}
func (m *AutoSelectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AutoSelectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AutoSelectResponse proto.InternalMessageInfo

func (m *AutoSelectResponse) GetServer() string {
	if m != nil {
		return m.Server
	}
	return ""
}

func init() {
	proto.RegisterType((*AutoSelectRequest)(nil), "proto.AutoSelectRequest")
	proto.RegisterType((*AutoSelectResponse)(nil), "proto.AutoSelectResponse")
}

func init() {
	proto.RegisterFile("cmd/mainservice-demo/proto/api.proto", fileDescriptor_46953b6d0e9afa48)
}

var fileDescriptor_46953b6d0e9afa48 = []byte{
	// 161 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x49, 0xce, 0x4d, 0xd1,
	0xcf, 0x4d, 0xcc, 0xcc, 0x2b, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0xd5, 0x4d, 0x49, 0xcd, 0xcd,
	0xd7, 0x2f, 0x28, 0xca, 0x2f, 0xc9, 0xd7, 0x4f, 0x2c, 0xc8, 0xd4, 0x03, 0xb3, 0x84, 0x58, 0xc1,
	0x94, 0x92, 0x3a, 0x97, 0xa0, 0x63, 0x69, 0x49, 0x7e, 0x70, 0x6a, 0x4e, 0x6a, 0x72, 0x49, 0x50,
	0x6a, 0x61, 0x69, 0x6a, 0x71, 0x89, 0x90, 0x10, 0x17, 0x4b, 0x5a, 0x51, 0x7e, 0xae, 0x04, 0xa3,
	0x02, 0xa3, 0x06, 0x67, 0x10, 0x98, 0xad, 0xa4, 0xc3, 0x25, 0x84, 0xac, 0xb0, 0xb8, 0x20, 0x3f,
	0xaf, 0x38, 0x55, 0x48, 0x8c, 0x8b, 0x0d, 0x64, 0x4b, 0x6a, 0x11, 0x54, 0x2d, 0x94, 0x67, 0xe4,
	0xcb, 0xc5, 0xe2, 0x92, 0x9a, 0x9b, 0x2f, 0xe4, 0xca, 0xc5, 0x87, 0xd0, 0xe5, 0x9b, 0x98, 0x99,
	0x27, 0x24, 0x01, 0xb1, 0x5f, 0x0f, 0xc3, 0x56, 0x29, 0x49, 0x2c, 0x32, 0x10, 0x6b, 0x92, 0xd8,
	0xc0, 0x32, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xdb, 0x0f, 0xc7, 0xaa, 0xdb, 0x00, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DemoClient is the client API for Demo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DemoClient interface {
	AutoSelectMain(ctx context.Context, in *AutoSelectRequest, opts ...grpc.CallOption) (*AutoSelectResponse, error)
}

type demoClient struct {
	cc grpc.ClientConnInterface
}

func NewDemoClient(cc grpc.ClientConnInterface) DemoClient {
	return &demoClient{cc}
}

func (c *demoClient) AutoSelectMain(ctx context.Context, in *AutoSelectRequest, opts ...grpc.CallOption) (*AutoSelectResponse, error) {
	out := new(AutoSelectResponse)
	err := c.cc.Invoke(ctx, "/proto.Demo/AutoSelectMain", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DemoServer is the server API for Demo service.
type DemoServer interface {
	AutoSelectMain(context.Context, *AutoSelectRequest) (*AutoSelectResponse, error)
}

// UnimplementedDemoServer can be embedded to have forward compatible implementations.
type UnimplementedDemoServer struct {
}

func (*UnimplementedDemoServer) AutoSelectMain(ctx context.Context, req *AutoSelectRequest) (*AutoSelectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AutoSelectMain not implemented")
}

func RegisterDemoServer(s *grpc.Server, srv DemoServer) {
	s.RegisterService(&_Demo_serviceDesc, srv)
}

func _Demo_AutoSelectMain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AutoSelectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DemoServer).AutoSelectMain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Demo/AutoSelectMain",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DemoServer).AutoSelectMain(ctx, req.(*AutoSelectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Demo_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Demo",
	HandlerType: (*DemoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AutoSelectMain",
			Handler:    _Demo_AutoSelectMain_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cmd/mainservice-demo/proto/api.proto",
}
