package(default_visibility = ["//skylb-api:__subpackages__"])

load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "go_default_library",
    srcs = ["flags.go"],
    importpath = "github.com/binchencoder/skylb-api/internal/flags",
)
